export const phonemeLegend: Record<string, string> = {
  θ: "TH (as in thin)",
  ð: "TH (as in this)",
  ʃ: "SH (as in ship)",
  ʒ: "ZH (as in vision)",
  tʃ: "CH (as in chin)",
  dʒ: "J (as in jam)",
  ŋ: "NG (as in ring)",
  ɪ: "I (as in sit)",
  e: "E (as in bed)",
  æ: "A (as in cat)",
  ʌ: "U (as in cup)",
  ɒ: "O (as in hot)",
  ʊ: "OO (as in book)",
  p: "P (as in pin)",
  b: "B (as in bat)",
  t: "T (as in top)",
  d: "D (as in dog)",
  k: "K (as in cat)",
  g: "G (as in go)",
  f: "F (as in fish)",
  v: "V (as in van)",
  s: "S (as in sun)",
  z: "Z (as in zoo)",
  h: "H (as in hat)",
  m: "M (as in map)",
  n: "N (as in net)",
  l: "L (as in leg)",
  r: "R (as in run/car)",
  w: "W (as in win)",
  j: "Y (as in yes)",
  ɑː: "AR (as in car, AU/UK)",
  ɑ: "O (as in car, US)",
  ɔː: "AW (as in water, AU/UK)",
  ə: "schwa — unstressed 'er' (AU/UK)",
  ɾ: "flap T (as in water, US)",
  ɚ: "R-colored schwa (as in water, US)",
};